//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op_is.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj predmet.
        /// </summary>
        public static string AddSubject {
            get {
                return ResourceManager.GetString("AddSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosecna Ocena.
        /// </summary>
        public static string AverageGrade {
            get {
                return ResourceManager.GetString("AverageGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponisti.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponisti.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zatvori.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drzava.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna Strana.
        /// </summary>
        public static string CurrentPage {
            get {
                return ResourceManager.GetString("CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna Godina Studiranja.
        /// </summary>
        public static string CurrentYearOfStudy {
            get {
                return ResourceManager.GetString("CurrentYearOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Rodjenja.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Obrisi.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katedre.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imejl.
        /// </summary>
        public static string E_mail {
            get {
                return ResourceManager.GetString("E-mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Uredi.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Upisa.
        /// </summary>
        public static string EnrollmentNumber {
            get {
                return ResourceManager.GetString("EnrollmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina Upisa.
        /// </summary>
        public static string EnrollmentYear {
            get {
                return ResourceManager.GetString("EnrollmentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espb.
        /// </summary>
        public static string Espb {
            get {
                return ResourceManager.GetString("Espb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fajl.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pomoc.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj licne karte.
        /// </summary>
        public static string IdCard {
            get {
                return ResourceManager.GetString("IdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Licne Karte.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeks.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije.
        /// </summary>
        public static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lokalizacija.
        /// </summary>
        public static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Novi.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naredna Strana.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Otvori.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polozi.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Telefona.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prethodna Strana.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesor.
        /// </summary>
        public static string Professor {
            get {
                return ResourceManager.GetString("Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesori.
        /// </summary>
        public static string Professors {
            get {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _StudentProfesori.
        /// </summary>
        public static string ProfessorsForStudent {
            get {
                return ResourceManager.GetString("ProfessorsForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni Ocenu.
        /// </summary>
        public static string RemoveGrade {
            get {
                return ResourceManager.GetString("RemoveGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni predmet.
        /// </summary>
        public static string RemoveSubject {
            get {
                return ResourceManager.GetString("RemoveSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sacuvaj.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestar.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_rpski.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pri_kaz.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentska služba.
        /// </summary>
        public static string StatusBarString {
            get {
                return ResourceManager.GetString("StatusBarString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student uslov predmet.
        /// </summary>
        public static string StudentConditionSubject {
            get {
                return ResourceManager.GetString("StudentConditionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ProfesorStudenti.
        /// </summary>
        public static string StudentsForProfessor {
            get {
                return ResourceManager.GetString("StudentsForProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka Smera.
        /// </summary>
        public static string StudyProgrammeMark {
            get {
                return ResourceManager.GetString("StudyProgrammeMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifra Predmeta.
        /// </summary>
        public static string SubjectCode {
            get {
                return ResourceManager.GetString("SubjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predmeti.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polozeni.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvanje.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepolozeni.
        /// </summary>
        public static string Unsubmitted {
            get {
                return ResourceManager.GetString("Unsubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Azuriraj.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina Studiranja.
        /// </summary>
        public static string YearOfStudy {
            get {
                return ResourceManager.GetString("YearOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godine staza.
        /// </summary>
        public static string YearsOfService {
            get {
                return ResourceManager.GetString("YearsOfService", resourceCulture);
            }
        }
    }
}
